class RachelPlayer : PlayerPawn
{
	Default
	{
		Speed 1;
		Health 100;
		Radius 16;
		Height 56;
		Mass 100;
		PainChance 255;
		Player.DisplayName "Rachel";
		Player.StartItem "RLP_BlasterA";
		Player.StartItem "Fist";
		Player.StartItem "Clip", 50;
		Player.WeaponSlot 1, "Fist", "Chainsaw";
		Player.WeaponSlot 2, "RLP_BlasterA";
		Player.WeaponSlot 3, "Shotgun", "SuperShotgun";
		Player.WeaponSlot 4, "Chaingun";
		Player.WeaponSlot 5, "RocketLauncher";
		Player.WeaponSlot 6, "PlasmaRifle";
		Player.WeaponSlot 7, "BFG9000";

		Player.ColorRange 200, 207;
		Player.Colorset 0, "$TXT_COLOR_DEFAULT",		200,207,203;
		Player.Colorset 1, "$TXT_COLOR_WHITE",			0,	17,	0;
		Player.Colorset 2, "$TXT_COLOR_GRAY",			4,	24,	12;
		Player.Colorset 3, "$TXT_COLOR_BLACK",			21,	31,	27;
		Player.Colorset 4, "$TXT_COLOR_RED",			32,	47,	40;
		Player.Colorset 5, "$TXT_COLOR_ORANGE",			49,	62,	55;
		Player.Colorset 6, "$TXT_COLOR_YELLOW",			73,	79,	76;
		Player.Colorset 7, "$TXT_COLOR_GREEN",			96,111,102;
		Player.Colorset 8, "$TXT_COLOR_AQUA",			120,127,123;
		Player.Colorset 9, "$TXT_COLOR_SKY",			128,139,133;
		Player.Colorset 10,"$TXT_COLOR_BLUE",			146,153,151;
		Player.Colorset 11,"$TXT_COLOR_PURPLE",			160,169,164;
		Player.Colorset 12,"$TXT_COLOR_MAGENTA",		179,187,184;
		+DECOUPLEDANIMATIONS
		+NOSKIN

	}
	States
	{
		Spawn:
			M000 A 1 SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
			Loop;
		See:
			M000 A 1 SetAnimation('Walk', 60, endFrame: 39, flags: SAF_LOOP|SAF_NOOVERRIDE);
			Loop;
		Melee:
		Missile:
			M000 A 20 SetAnimation('Fire', 40, loopFrame: 9, flags: SAF_LOOP|SAF_NOOVERRIDE);
			Goto Spawn;
		Pain:
			M000 A 4 SetAnimation('Hurt');
			M000 A 4 A_Pain;
			Goto Spawn;
		Death:
		XDeath:
			M000 A 10 SetAnimation('Death');
			M000 A 10 A_PlayerScream;
			M000 A -1 A_NoBlocking;
			Stop;

	}
}