class RachelPlayer : DoomPlayer
{
	Default
	{
		Speed 1;
		Health 100;
		Radius 16;
		Height 56;
		Mass 100;
		PainChance 255;
		Player.DisplayName "Rachel";
		Player.StartItem "RLP_BlasterA";
		Player.StartItem "Fist";
		Player.StartItem "Clip", 50;
		Player.WeaponSlot 1, "Fist", "Chainsaw";
		Player.WeaponSlot 2, "RLP_BlasterA";
		Player.WeaponSlot 3, "Shotgun", "SuperShotgun";
		Player.WeaponSlot 4, "Chaingun";
		Player.WeaponSlot 5, "RocketLauncher";
		Player.WeaponSlot 6, "PlasmaRifle";
		Player.WeaponSlot 7, "BFG9000";

		Player.ColorRange 200, 207;
		Player.Colorset 0, "$TXT_COLOR_GREEN",		0x70, 0x7F,  0x72;
		Player.Colorset 1, "$TXT_COLOR_GRAY",		0x60, 0x6F,  0x62;
		Player.Colorset 2, "$TXT_COLOR_BROWN",		0x40, 0x4F,  0x42;
		Player.Colorset 3, "$TXT_COLOR_RED",		0x20, 0x2F,  0x22;
		// Doom Legacy additions
		Player.Colorset 4, "$TXT_COLOR_LIGHTGRAY",	0x58, 0x67,  0x5A;
		Player.Colorset 5, "$TXT_COLOR_LIGHTBROWN",	0x38, 0x47,  0x3A;
		Player.Colorset 6, "$TXT_COLOR_LIGHTRED",	0xB0, 0xBF,  0xB2;
		Player.Colorset 7, "$TXT_COLOR_LIGHTBLUE",	0xC0, 0xCF,  0xC2;
		+DECOUPLEDANIMATIONS
		+NOSKIN

	}
	States
	{
		Spawn:
			M000 A 1 SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
			Loop;
		See:
			M000 A 1 SetAnimation('Walk', 60, endFrame: 39, flags: SAF_LOOP|SAF_NOOVERRIDE);
			Loop;
		Melee:
		Missile:
			M000 A 20 SetAnimation('Fire', 40, loopFrame: 9, flags: SAF_LOOP|SAF_NOOVERRIDE);
			Goto Spawn;
		Pain:
			M000 A 4 SetAnimation('Hurt');
			M000 A 4 A_Pain;
			Goto Spawn;
		Death:
		XDeath:
			M000 A 10 SetAnimation('Death');
			M000 A 10 A_PlayerScream;
			M000 A -1 A_NoBlocking;
			Stop;

	}
}