#include "./Weapons/RLP_EveningStar.zsc"
#include "./Weapons/RLP_Kahuna.zsc"
#include "./Weapons/RLP_MissileLauncher.zsc"

class RLP_Weapon : Weapon
{
	action bool JustPressed(int which) // "which" being any BT_* value, mentioned above or not
	{
		return player.cmd.buttons & which && !(player.oldbuttons & which);
	}
	Default
	{
		Weapon.Kickback 100;
		Weapon.BobStyle "Smooth";
		Weapon.BobRangeX 1.0;
		Weapon.BobRangeY 1.0;
		Weapon.BobSpeed 1.0;
	}
}