version "4.12.2"

#include "ZScript/Player.zsc"
#include "ZScript/HUD.zsc"

// Weapons & Items
#include "ZScript/Weapons.zsc"
#include "ZScript/Items.zsc"

// Friends
#include "ZScript/Friends.zsc"

// Enemies
#include "ZScript/Enemies.zsc"

// Universal Weapon Sway
#include "ZScript/sway/sway.zsc"
#include "ZScript/sway/menu.zsc"

// ZFootsteps
#include "ZScript/StepEventHandler.zsc"

// ZScript Weapon Library
#include "ZScript/ZWL/zwl.zs"