class RLP_Shell : Ammo
{
	Default
	{
		//$Category "Ammunition
		//$Title "Shells
		Inventory.PickupMessage "$GOTSHELLS"; // "Picked up a small box of shells."
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "SHELA0";
	}
	States
	{
 		Spawn:
			M000 A -1;
			Stop;
	}
}

class RLP_MissileAmmo : Ammo
{
	Default
	{
		//$Category "Ammunition
		//$Title "Missile
		Inventory.PickupMessage "$GOTMISSILE"; // "Picked up a missile."
		Inventory.Amount 1;
		Inventory.MaxAmount 30;
		Ammo.BackpackAmount 5;
		Ammo.BackpackMaxAmount 60;
		Inventory.Icon "ROCKA0";
	}
	States
	{
		Spawn:
			ROCK A -1;
			Stop;
	}
}

class RLP_Scrap : Ammo
{
	Default
	{
		//$Category "Ammunition
		//$Title "Missile
		Inventory.PickupMessage "$GOTMISSILE"; // "Picked up a missile."
		Inventory.Amount 1;
		Inventory.MaxAmount 30;
		Ammo.BackpackAmount 5;
		Ammo.BackpackMaxAmount 60;
		Inventory.Icon "ROCKA0";
	}
	States
	{
		Spawn:
			ROCK A -1;
			Stop;
	}
}