class RLP_JuiceCan : Health
{
	Default
	{
		//$Category "Health and Armor"
		//$Title "Juice Can
		Inventory.Amount 3;
		Inventory.PickupMessage "$GOTJUICE"; // "Drank a can of juice."
	}
	States
	{
		Spawn:
			// currently no alt skins since it's a whole-ass colormap
//			M000 A 0 NoDelay A_Jump(256, "Placeholder", "Placeholder2");
//			Stop;
//		Placeholder:
//			M000 A -1 A_ChangeModel("", skinindex: 0, skinpath: "Models/Pickups/", skin: "can1.png");
//			Stop;
//		Placeholder2:
//			M000 A -1 A_ChangeModel("", skinindex: 0, skinpath: "Models/Pickups/", skin: "can2.png");
//			Stop;
			M000 A -1;
			Stop;
	}
}