class RLP_RobotBug : Actor
{
	Default
	{
		//$Title "Robot Bug
		//$Category "Monsters"
		BloodColor "370000";
		Tag "$TAG_ROBOTBUG";
		Health 60;
		Monster;
		Height 32;
		Radius 28;
		Speed 8;
		+DECOUPLEDANIMATIONS
		DamageFactor "Kick", 0.5;
	}
	States
	{
		Spawn:
			M000 A 1 {
				SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
				A_Look();
			}
			Loop;
		See:
			M000 AAA 1 {
				SetAnimation('Walk', 60, flags: SAF_LOOP|SAF_NOOVERRIDE);
				A_Chase(); // replace with zscript pathfinding shit later
			}
			M000 A 1 {
				SetAnimation('Walk', 60, flags: SAF_LOOP|SAF_NOOVERRIDE);
			}
			Loop;
	}
}