class RLP_RobotBug : RLP_Monster
{
	Default
	{
		//$Title "Robot Bug
		//$Category "Monsters"
		BloodColor "370000";
		Tag "$TAG_ROBOTBUG";
		Health 120;
		Height 28;
		Radius 21;
		Speed 6;
		DamageFactor "Kick", 0.5;
		DamageFactor "Drill", 2;
		MeleeRange 44*5;
	}
	States
	{
		Spawn:
			M000 A 1 {
				SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
				A_Look();
			}
			Loop;
		See:
			M000 A 1 {
				SetAnimation('Walk', 60, flags: SAF_LOOP|SAF_NOOVERRIDE);
				A_PortedChase();
			}
			Loop;
/*		Melee:
			M000 AAAAA 4 {
				SetAnimation('Charge', 60, flags: SAF_NOOVERRIDE);
				A_FaceTarget();
			}
			M000 AAA 1 {
				VelFromAngle(Self.Speed*4);
//				A_CustomMeleeAttack()
			}
			M000 AAAAAAAA 1;
			Goto Spawn;*/
		Death:
			M000 A -1 {SetAnimation('Dead');}
			Stop;
	}
}