class RLP_BlasterA : RLP_Weapon
{
	Default
	{
		Weapon.SelectionOrder 1900;
		Obituary "$OB_BLASTER_A";
		+WEAPON.WIMPY_WEAPON
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "$PICKUP_BLASTER_A";
		Tag "$TAG_BLASTER_A";
		+DECOUPLEDANIMATIONS
	}
	States
	{
		Ready:
			M000 A 1 {
				A_WeaponReady();
				invoker.SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
			}
			Loop;
		Select:
			M000 A 1 {
				A_Raise(18);
				invoker.Translation = self.Translation;
				invoker.SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
			}
			Loop;
		Deselect:
			M000 A 1 {
				A_Lower(18);
				invoker.SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);
			}
			Loop;
		Fire:
			M000 A 4 {
				A_FireProjectile("Rocket");
				invoker.SetAnimation('Fire');
			}
			M000 AAAAAAAA 1 A_WeaponReady;
			M000 A 0 A_ReFire;
			Goto Ready;
		Spawn:
			PIST A -1 {invoker.SetAnimation('Idle', flags: SAF_LOOP|SAF_NOOVERRIDE);}
			Stop;
	}
}